COMMON: &common #标识
  DEBUG: False
  TESTING: False
  THREADED: False
  SECRET_KEY: insecure

  #数据库连接
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root@127.0.0.1:3306/rongv?charset=utf8mb4'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  #日志文件
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  LOGGING_PATH: ./logs
  RESPONSE_MESSAGE: ./config/msg.yaml

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  ENV:  dev
TESTING: &testing
  <<: *common
  ENV: test
  TESTING: True

PRODUCTION: &production
  <<: *common
  ENV: prod
  SECRET_KEY: shouldbereallysecureatsomepoint

